name: "Compile"
description: "Executes a compilation."

inputs:
  path:
    required: true
    description: "Path to compile and test"
    default: src/
  build_path:
    required: true
    description: "Path to built files"

runs:
  using: "composite"
  steps:
    - name: Generate CMake project
      run: |
        SRC_FOLDER=$(pwd)/${{ inputs.path }}
        mkdir -p ${{ inputs.build_path }} && cd ${{ inputs.build_path }}
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Visual Studio 17 2022" -A x64
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Unix Makefiles"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -DENABLE_CLANG_TIDY=NO -G "Unix Makefiles"
        else
          echo "Unsupported OS: $RUNNER_OS"
          exit 1
        fi
        echo "CMake project generated in $(pwd)"
      shell: bash

    - name: Compile
      run: |
        cd ${{ inputs.build_path }}
        if [ ! -f CMakeCache.txt ]; then
          echo "CMake cache not found in $(pwd). Aborting."
          exit 1
        fi
        cmake --build . --config RelWithDebInfo -j $(nproc)
      shell: bash
