run-name: Package - Upload Docker package building images
name: Package - Upload Docker package building images

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'main'
    paths:
      - 'packages/**'

jobs:
  Upload-package-building-images:
    runs-on: ubuntu-24.04

    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout wazuh/wazuh repository
        uses: actions/checkout@v4

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            pkg_deb_agent_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/amd64/agent/**'
              - 'packages/debs/utils/**'
            pkg_deb_agent_builder_i386:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/i386/agent/**'
              - 'packages/debs/utils/**'
            pkg_deb_agent_builder_ppc64le:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/ppc64le/agent/**'
              - 'packages/debs/utils/**'
            pkg_rpm_agent_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/amd64/agent/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_agent_builder_i386:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/i386/agent/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_agent_builder_ppc64le:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/ppc64le/agent/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_legacy_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/amd64/legacy/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_legacy_builder_i386:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/i386/legacy/**'
              - 'packages/rpms/utils/**'
            pkg_deb_agent_builder_arm64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/arm64/agent/**'
              - 'packages/debs/utils/**'
            pkg_deb_agent_builder_armhf:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/armhf/agent/**'
              - 'packages/debs/utils/**'
            pkg_rpm_agent_builder_arm64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/arm64/agent/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_agent_builder_armhf:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/armhf/agent/**'
              - 'packages/rpms/utils/**'
            compile_windows_agent:
              - 'packages/windows/**'
            commom_wpk_builder:
              - 'packages/wpk/wpkpack.py'
              - 'packages/wpk/run.sh'
              - 'packages/wpk/generate_wpk_package.sh'
              - 'packages/wpk/common/**'

      - name: Set TAG and WAZUH_AGENT_PACKAGES_BRANCH
        run: |
          VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION.json)"
          echo "TAG=$VERSION" >> $GITHUB_ENV;

      - name: Request pkg_deb_agent_builder_amd64 update
        if: steps.changes.outputs.pkg_deb_agent_builder_amd64 == 'true'
        run: |
          gh workflow run 6_builderpackage_upload-images-linux.yml --repo wazuh/wazuh-agent-packages -r ${{ github.ref_name }} -f docker_image_tag=${{ env.TAG }} -f system=deb -f architecture=amd64 -f source_reference=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.CI_WAZUH_AGENT_PACKAGES }}

      - name: Request pkg_rpm_agent_builder_amd64 update
        if: steps.changes.outputs.pkg_rpm_agent_builder_amd64 == 'true'
        run: |
          gh workflow run 6_builderpackage_upload-images-linux.yml --repo wazuh/wazuh-agent-packages -r ${{ github.ref_name }} -f docker_image_tag=${{ env.TAG }} -f system=rpm -f architecture=amd64 -f source_reference=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.CI_WAZUH_AGENT_PACKAGES }}

      - name: Request pkg_deb_agent_builder_arm64 update
        if: steps.changes.outputs.pkg_deb_agent_builder_arm64 == 'true'
        run: |
          gh workflow run 6_builderpackage_upload-images-linux.yml --repo wazuh/wazuh-agent-packages -r ${{ github.ref_name }} -f docker_image_tag=${{ env.TAG }} -f system=deb -f architecture=arm64 -f source_reference=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.CI_WAZUH_AGENT_PACKAGES }}

      - name: Request pkg_rpm_agent_builder_arm64 update
        if: steps.changes.outputs.pkg_rpm_agent_builder_arm64 == 'true'
        run: |
          gh workflow run 6_builderpackage_upload-images-linux.yml --repo wazuh/wazuh-agent-packages -r ${{ github.ref_name }} -f docker_image_tag=${{ env.TAG }} -f system=rpm -f architecture=arm64 -f source_reference=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.CI_WAZUH_AGENT_PACKAGES }}
