name: 'Compile Mac OS Repository'
description: 'Compile Mac OS Repository'
inputs:
  architecture:
    description: 'Building architecture'
    required: true
  gh_token:
    description: 'Used token to fetch dependencies'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Binary caching
      uses: ./.github/actions/vcpkg_related/6_builderpackage_vcpkg
      with:
        gh_token: ${{ inputs.gh_token }}

    - name: Setup CMake 3.x
      uses: ./.github/actions/6_builderprecompiled_cmake

    - name: Build repository
      shell: bash
      run: |
        cmake -B build src
        cmake --build build -j $(sysctl -n hw.ncpu)
        cmake --install build --prefix install

        sudo rm -rf build/_deps build/vcpkg_installed
        zip -r wazuh-agent-binaries-${{ inputs.architecture }}.zip .

    - name: Upload wazuh-agent-binaries.zip
      uses: actions/upload-artifact@v4
      with:
        name: wazuh-agent-binaries-${{ inputs.architecture }}
        path: ${{ github.workspace }}/wazuh-agent-binaries-${{ inputs.architecture }}.zip
